### ISSUE TITLE
Mirror to GitLab

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rpm-spec-automake116-automake#1]
@ribose-jeffreylau When you get a chance can you mirror this to the `ribose/rpm-spec` group?

**Comment by ronaldtse** [comment]
Ping @ribose-jeffreylau

**Comment by ribose-jeffreylau** [comment]
@dewyatt [Done](https://gitlab.com/ribose/rpm-spec/rpm-spec-automake116-automake).

_P.S._ I had to first import to my personal GitLab user namespace, then transfer it to `rpm-spec/`, or else it would fail with a 422 error the moment I clicked <kbd>Import</kbd>.  Couldn't figure out why.  (It also happened with `rpm-spec-rbenv-ruby-2.5.5` and `rpm-spec-rbenv-ruby-2.6.2`.)

**Comment by dewyatt** [comment]
Thanks @ribose-jeffreylau ! 
Yeah I've been having the same issue with GitLab importing, so it sounds like a bug. I'll check to see if it has been reported.

**Comment by dewyatt** [comment]
@ribose-jeffreylau Just FYI, looks like this would be https://gitlab.com/gitlab-org/gitlab-ce/issues/47327.

It looks like it fails to import if the Group visibility level is anything other than Public. The import+transfer works because it ends up automatically changing the Project visibility to match the Group.

Anyways, it may help to give that issue a thumbs up, IIRC that's one of the ways they prioritize.

**Comment by dewyatt** [comment]
Oops and I forgot to close this. Thanks!

**Comment by ribose-jeffreylau** [comment]
Good find @dewyatt !  I gave it a thumbs up.  Now 🤞 !
