### ISSUE TITLE
Upgrade to 1.16.3

### ISSUE THREAD

**Issue by maxirmx** [riboseinc/rpm-spec-automake116-automake#2]
RNP project requires automake version 1.16.3+ due to GnuPG 2.3 build requirements
Is it possible to upgrade this spec, please ?

**Comment by ronaldtse** [comment]
Ping @ni4 @antonsviridenko @ribose-jeffreylau

**Comment by ribose-jeffreylau** [comment]
Fixed with https://github.com/riboseinc/rpm-spec-automake116-automake/commit/513c404734a91ceb410c5a70ca21565cad850126

@maxirmx  Please check if OK, thanks!

**Comment by ni4** [comment]
@maxirmx Hm, we already used GnuPG 2.3.1, and since the following commit 2.4.0 : https://github.com/rnpgp/rnp/commit/54156da47df38c875ffaa2cf7a9ea7c2ba17b195

**Comment by maxirmx** [comment]
@ni4, yes we are using GnuPG and setup script does the following:

- installs automake from CentOS repo (below 1.16)
- installs automake 1.16.1 from ribose repo ontop
- builds automale 1.16.4 from source
- uninstalls automake from ribose

This does not look correct

**Comment by ni4** [comment]
Ah, got it. Thanks for explanation.

**Comment by maxirmx** [comment]
> 

> Fixed with [513c404](https://github.com/riboseinc/rpm-spec-automake116-automake/commit/513c404734a91ceb410c5a70ca21565cad850126)
> 
> @maxirmx Please check if OK, thanks!

Thank you, it is OK
